### ISSUE TITLE
Add a semver oriented version object

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/assembler#10]
As with the component package - This package also should export a semver oriented version object for future compatibility checks.

https://github.com/reduct/component/blob/master/Src/Component.js#L23

**Comment by grebaldi** [comment]
We should automate this for all packages, since we can easily aggregate that information from package.json during build.

**Comment by Inkdpixels** [comment]
Yeah! That would be great! I've created a corresponding issue here:
https://github.com/reduct/shared-build/issues/1

**Comment by Inkdpixels** [comment]
Closed since it's included in the refactoring branch and will be merged soon.
