### ISSUE TITLE
The already instantiated elements index doesn't work properly

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/assembler#23]
Since the new 1.0.0 version, the index of already instantiated elements doesn't work anymore. Could you take a look at this @akoenig?

For an example see https://jsbin.com/xazomowoye/edit?html,js,console,output

In the example above, I am parsing the document over and over again, and the component gets mounted each time, though it was already mounted before.

**Comment by akoenig** [comment]
Jap, will take care of this. It is due to the fact, that there is no additional check on an element basis anymore.

**Comment by akoenig** [comment]
In the `development` branch and ready for release `1.0.1`.
